### ISSUE TITLE
Swedish Translation 

### ISSUE THREAD

**Issue by Refutable13** [mty22/krunker.io-translations#215]
I am aware there has been issues regarding Swedish translation before. However, I hope the time may finally have come to introduce Swedish to krunker.io. Swedish is my native language and I would happily contribute to this project. I could also have it finished rather quickly for that matter. 

Best regards.

**Comment by mty22** [comment]
Hello!

Thanks for the interest! We're currently not looking to translate Krunker into Swedish.

Keep in mind that in order to be eligible for KR payouts, the language must be approved first. With that being said, you are still welcome to translate it although it won't be added to the game.

Thanks!
