### ISSUE TITLE
Ukrainian language! (v3.8.1)

### ISSUE THREAD

**Issue by realTiXoNyA** [mty22/krunker.io-translations#72]

**Comment by mty22** [comment]
Hi, I'll get back to you on that one.

**Comment by realTiXoNyA** [comment]
our small team of translators made sketches of the translation into this language, we are ready to provide translation from 24 hours to two days if necessary

**Comment by Tarikus252** [comment]
@realTiXoNyA   , so you are working on it?

**Comment by Yurikan4ik** [comment]
@Tarikus252 hello! We have already done with Ukrainian translation.

**Comment by mty22** [comment]
For now, we will stick with Russian translation. Thank you for the interest. If we add Ukrainian, I'll get in contact with you.

**Comment by mty22** [comment]
![image](https://user-images.githubusercontent.com/2951231/146778992-4f7d4ff5-be1c-42fd-be75-7fa2b6d39159.png)

Escalated

**Comment by mty22** [comment]
![image](https://user-images.githubusercontent.com/2951231/151694250-2a225d0e-a327-4bf7-b991-5ee1233ae11c.png)

Only a few more upvotes added since 21/DEC/2021. The Krunker RU Discord server has around 750-800 players in it, so its around 15% wanting it.

Will defer and observe, although for now it's unlikely we will add it to the game.

**Comment by mty22** [comment]
Due to current events in Ukraine, it's best if we hold on this for now.

Happy to re-visit once things settle down. Health and safety comes first.

**Comment by mty22** [comment]
Closing until we can re-visit in future.
